<?php

declare(strict_types=1);

namespace LaravelUi5\OData\Service\Cache;

use LaravelUi5\OData\Edm\Contracts\EdmxInterface;
use LaravelUi5\OData\Service\Contracts\ODataServiceInterface;
use ReflectionClass;

/**
 * Loads a cached EdmxInterface from the generated Edm\ directory next to a service class.
 *
 * The cache is a set of PHP readonly classes generated by EdmxWriter. The root class
 * is always {ServiceNamespace}\Edm\Edmx and lives at {ServiceDir}/Edm/Edmx.php.
 */
final class EdmxLoader
{
    /**
     * Attempt to load a cached EdmxInterface for the given service.
     *
     * Returns null when no cache exists (the service should fall back to EdmBuilder).
     */
    public static function forService(ODataServiceInterface $service): ?EdmxInterface
    {
        // Check the file exists before class_exists() to avoid autoloader
        // errors when the cache directory has been cleared but the in-memory
        // classmap still references the deleted files.
        $cacheFile = self::cacheDir($service) . '/Edmx.php';
        if (!file_exists($cacheFile)) {
            return null;
        }

        $edmxClass = self::edmxClassName($service);

        if (!class_exists($edmxClass)) {
            return null;
        }

        $instance = new $edmxClass();

        return $instance instanceof EdmxInterface ? $instance : null;
    }

    /**
     * Derive the FQCN of the cached Edmx class from a service instance.
     *
     * Convention: {ServiceClassNamespace}\Edm\Edmx
     */
    public static function edmxClassName(ODataServiceInterface $service): string
    {
        $refl = new ReflectionClass($service);
        return $refl->getNamespaceName() . '\\Edm\\Edmx';
    }

    /**
     * Derive the filesystem directory where cached Edm files live.
     *
     * Convention: {ServiceClassDir}/Edm/
     */
    public static function cacheDir(ODataServiceInterface $service): string
    {
        $refl = new ReflectionClass($service);
        return dirname($refl->getFileName()) . '/Edm';
    }
}
