<?php

declare(strict_types=1);

namespace LaravelUi5\OData\Service\Cache;

use LaravelUi5\OData\Service\Contracts\ODataServiceInterface;
use LaravelUi5\OData\Service\Resolver\CustomBinding;
use LaravelUi5\OData\Service\Resolver\EloquentBinding;
use LaravelUi5\OData\Service\Resolver\ResolverMap;
use LaravelUi5\OData\Service\Resolver\SqlBinding;
use LaravelUi5\OData\Service\Resolver\SqlSourceBinding;
use ReflectionClass;

/**
 * Generates a PHP file containing a cached ResolverMap for a service.
 *
 * The generated file is a readonly class with a static load() method that
 * reconstructs the ResolverMap from plain PHP — no reflection, no DB calls.
 */
final class ResolverMapWriter
{
    /**
     * Write the ResolverMap as a PHP file to the service's Edm/ cache directory.
     */
    public static function write(ODataServiceInterface $service, ResolverMap $map): void
    {
        $refl = new ReflectionClass($service);
        $namespace = $refl->getNamespaceName() . '\\Edm';
        $dir = dirname($refl->getFileName()) . '/Edm';

        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        $bindings = self::renderBindings($map);

        $php = <<<PHP
        <?php

        declare(strict_types=1);

        namespace {$namespace};

        use LaravelUi5\\OData\\Service\\Resolver\\CustomBinding;
        use LaravelUi5\\OData\\Service\\Resolver\\EloquentBinding;
        use LaravelUi5\\OData\\Service\\Resolver\\ResolverMap as BaseResolverMap;
        use LaravelUi5\\OData\\Service\\Resolver\\SqlBinding;
        use LaravelUi5\\OData\\Service\\Resolver\\SqlSourceBinding;

        /**
         * Generated by odata:cache — do not edit.
         */
        final readonly class ResolverMap
        {
            public static function load(): BaseResolverMap
            {
                return new BaseResolverMap([
        {$bindings}
                ]);
            }
        }

        PHP;

        file_put_contents($dir . '/ResolverMap.php', $php);
    }

    private static function renderBindings(ResolverMap $map): string
    {
        $lines = [];

        foreach ($map->getBindings() as $entitySetName => $binding) {
            $key = var_export($entitySetName, true);

            $line = match (true) {
                $binding instanceof EloquentBinding => sprintf(
                    "            %s => new EloquentBinding(%s),",
                    $key,
                    '\\' . $binding->modelClass . '::class',
                ),
                $binding instanceof SqlBinding => $binding->connection !== null
                    ? sprintf(
                        "            %s => new SqlBinding(%s, %s),",
                        $key,
                        var_export($binding->table, true),
                        var_export($binding->connection, true),
                    )
                    : sprintf(
                        "            %s => new SqlBinding(%s),",
                        $key,
                        var_export($binding->table, true),
                    ),
                $binding instanceof SqlSourceBinding => sprintf(
                    "            %s => new SqlSourceBinding(%s),",
                    $key,
                    '\\' . $binding->sourceClass . '::class',
                ),
                $binding instanceof CustomBinding => sprintf(
                    "            %s => new CustomBinding(%s),",
                    $key,
                    '\\' . $binding->resolverClass . '::class',
                ),
                default => throw new \RuntimeException(
                    sprintf('Unknown binding type: %s', get_class($binding))
                ),
            };

            $lines[] = $line;
        }

        return implode("\n", $lines);
    }
}
