<?php

declare(strict_types=1);

namespace LaravelUi5\OData\Edm\Contracts\Annotation;

use LaravelUi5\OData\Edm\Contracts\Annotation\AnnotationInterface;
use LaravelUi5\OData\Edm\Contracts\AnnotationTargetInterface;

/**
 * Contract for generated, typed annotation classes.
 *
 * Every class generated from a vocabulary Term implements this interface.
 * It provides three things: the fully qualified term name as a constant
 * for static reference, the set of valid annotation targets as an array
 * of class-string values for static analysis, and a bridge method that
 * converts the typed object into the generic AnnotationInterface used
 * throughout the EDM contract layer.
 *
 * Implementing classes are generated by the vocabulary generator and
 * committed to the repository. They are never instantiated at runtime
 * by the parser; they are instantiated by the SchemaBuilder when
 * attaching annotations to model elements.
 *
 * Example usage in a SchemaBuilder:
 *
 *   $annotation = new \LaravelUi5\OData\Vocabularies\Ui\V1\LineItem(
 *       value: [$dataField1, $dataField2],
 *   );
 *   // Validate target at build time (via static analysis or assertion):
 *   // LineItem::APPLIES_TO contains EntityTypeInterface::class
 *   $entityType->addAnnotation($annotation->toAnnotation());
 *
 * Example of APPLIES_TO in a generated class:
 *
 *   public const array APPLIES_TO = [
 *       \LaravelUi5\OData\Edm\Contracts\Type\EntityTypeInterface::class,
 *       \LaravelUi5\OData\Edm\Contracts\Container\EntitySetInterface::class,
 *   ];
 */
interface TypedAnnotationInterface
{
    /**
     * The fully qualified term name, e.g.
     * "com.sap.vocabularies.UI.v1.LineItem".
     *
     * This constant is defined on each generated class and never changes.
     * It is used as the storage key in AnnotationInterface::getTerm() and
     * as the lookup key in AnnotatableInterface::getAnnotation().
     */
    public const string TERM = '';

    /**
     * The model element types this annotation may legally be applied to,
     * expressed as an array of class-string values referencing interfaces
     * that extend AnnotationTargetInterface.
     *
     * Defined as a constant on each generated class. PHPStan and Psalm
     * use this to flag misapplied annotations at analysis time.
     *
     * @var array<class-string<AnnotationTargetInterface>>
     */
    public const array APPLIES_TO = [];

    /**
     * The optional qualifier for this annotation instance. Null when
     * no qualifier is needed.
     *
     * @see OData CSDL XML v4.01 §14.2.1 (Qualifier)
     */
    public function getQualifier(): ?string;

    /**
     * Converts this typed annotation into the generic AnnotationInterface
     * used by the EDM contract layer and the serialiser.
     *
     * The returned AnnotationInterface must carry the fully qualified term
     * name from TERM as its getTerm() value, and must represent the typed
     * value faithfully as a ConstantAnnotationValueInterface,
     * RecordAnnotationValueInterface, or CollectionAnnotationValueInterface.
     */
    public function toAnnotation(): AnnotationInterface;
}