<?php

declare(strict_types=1);

namespace LaravelUi5\OData\Edm\Annotation;

use LaravelUi5\OData\Edm\Annotation\Annotation;
use LaravelUi5\OData\Edm\Contracts\Annotation\AnnotationInterface;
use LaravelUi5\OData\Edm\Contracts\Annotation\AnnotationValueInterface;

/**
 * Shared implementation for classes generated from OData vocabulary Terms.
 *
 * Every class generated by the vocabulary generator uses this trait.
 * It provides:
 *   - getQualifier()      — reads $this->qualifier declared by the using class
 *   - toAnnotation()      — constructs an Annotation from TERM, qualifier, and value
 *   - buildAnnotationValue() (abstract) — each generated class maps its own typed
 *                            constructor arguments to ConstantAnnotationValue,
 *                            RecordAnnotationValue, or CollectionAnnotationValue
 *
 * The trait never inspects the using class's properties directly other than
 * $qualifier. All typed property access is delegated to buildAnnotationValue().
 *
 * @see TypedAnnotationInterface
 */
trait TypedAnnotationTrait
{
    /**
     * Returns the optional annotation qualifier, or null when absent.
     *
     * Reads $this->qualifier which every generated class declares as
     * `public readonly ?string $qualifier = null` in its constructor.
     */
    public function getQualifier(): ?string
    {
        return $this->qualifier;
    }

    /**
     * Converts this typed annotation into the generic AnnotationInterface
     * used throughout the EDM contract layer.
     *
     * The term name is taken from the class constant TERM; the qualifier
     * from getQualifier(); the value from buildAnnotationValue().
     */
    final public function toAnnotation(): AnnotationInterface
    {
        return new Annotation(
            static::TERM,
            $this->getQualifier(),
            $this->buildAnnotationValue(),
        );
    }

    /**
     * Maps the typed constructor arguments of the using class to the
     * appropriate annotation value object.
     *
     * Implementations return a ConstantAnnotationValue for primitive
     * terms, a RecordAnnotationValue for record terms, a
     * CollectionAnnotationValue for collection terms, and null for
     * Boolean marker terms whose presence alone carries the meaning.
     */
    abstract protected function buildAnnotationValue(): ?AnnotationValueInterface;
}
